### ISSUE TITLE
Custom data of a contact is not cleared

### ISSUE THREAD

**Issue by jaapjansma** [systopia/de.systopia.anonymiser#12]
When anonymizing a contact custom data is not cleared.

The same is true for example when one wants to keep the event registration (participant record) and anonymize them. The custom data is not cleared either.

**Comment by bjendres** [comment]
Yes, it says "anonymises contact base data" in the docs. But feel free to create a feature request. Or should we use this ticket...?

**Comment by jaapjansma** [comment]
I am going to provide a fix for this probably today or tomorrow. I my use case the custom data also needs to be cleared. 
I am not sure how to interpret 'contact base data'. Does not include custom data or exclude.

**Comment by jaapjansma** [comment]
I have submitted a PR. The PR basically clears all custom data. The reason for clearing all related custom data (to a participant, membership, contact etc...) is that I don't see a usecase where one wants to keep certain data but still wants to anonymize the contact. If that is the case we can easily build on top of this PR a settings screen to exclude certain custom groups for being cleared.

**Comment by bjendres** [comment]
> 'contact base data'. Does not include custom data or exclude.

In my head it was only the contact data in out-of-the-box CiviCRM, without any related entities or custom fields. But this should probably be clarified in the UI. Any suggestions?

> I don't see a usecase where one wants to keep certain data but still wants to anonymize the contact. 

I can, if you want to use the anoymiser and still want to keep all your registration stats, but that can then be funded by somebody else.

**Comment by jaapjansma** [comment]
Thanks for merging.

> I can, if you want to use the anoymiser and still want to keep all your registration stats, but that can then be funded by somebody else.

Yes when this use case pops up we will probably have funding for that.
