### ISSUE TITLE
Create 'runner' to anonymise a selection of contacts

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.anonymiser#7]
It would be great if we could anonymise multiple contacts in one run.

**Comment by jaapjansma** [comment]
I am not sure what you mean with runner. In the use case I will be working on we want to bulk anonymize contacts after a search. The easiest solution for me is to integrate this extension with the action provider and then the action is available in the [Search Action Designer extension](https://lab.civicrm.org/extensions/searchactiondesigner).

**Comment by jaapjansma** [comment]
Ah ok. I will see what I can contribute as I have some funding towards this.
