### ISSUE TITLE
Keep certain data

### ISSUE THREAD

**Issue by jaapjansma** [systopia/de.systopia.anonymiser#9]
In my use case we want to delete all data but keep the following:

* Link between the contact and an event (in my use case it is children who participated in a summer camp)
* The gender
* The age (at the moment the summer camp took place)
* Anonymised/Pseudomized name of the contact

Regarding the gender and age we can store that in custom fields on the participant record as well. We can then use the anonymize contact (as proposed in #8). But we still need to move/keep the participant record.

**Comment by jaapjansma** [comment]
I took a dive into the code and what is needed is a configuration and settings page. I will work on that first

**Comment by bjendres** [comment]
@jaapjansma what is the status of this? Is this already implemented with ``1.1.0``?

**Comment by bjendres** [comment]
Thanks. I released a ``1.1.1`` now, but if you have more features it would be great if you could create some PRs whenever you have the time.
